name = "CellBasedModels"
uuid = "388cb286-f2b1-4654-a3bb-2e137a39c658"
authors = ["Gabriel Torregrosa Cort√©s"]
version = "0.1.1"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEqDifferentiation = "4302a76b-040a-498a-8c04-15b101fed76b"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CellBasedModelsGPUCudaExt = "CUDA"

[compat]
ADTypes = "1.18.0"
Adapt = "4.4.0"
ArrayInterface = "7.20.0"
BenchmarkTools = "1.6.0"
CSV = "0.10, 1"
CUDA = "4, 5"
CairoMakie = "0.15.7"
DataFrames = "1, 2"
DifferentialEquations = "7"
Distributions = "0.25, 1"
ForwardDiff = "1.3.0"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
InteractiveUtils = "1.11.0"
JLD2 = "0.4, 1"
KernelAbstractions = "0.9.39"
Logging = "1.11.0"
MacroTools = "0.5"
OrderedCollections = "1"
OrdinaryDiffEqDifferentiation = "1.16.1"
PProf = "3.2.0"
Printf = "1.11.0"
Profile = "1.11.0"
ProgressMeter = "1.7"
RecursiveArrayTools = "3.37.1"
SparseConnectivityTracer = "1.1.2"
SpecialFunctions = "2"
StaticArrays = "1.9.15"
StaticArraysCore = "1.4.3"
SymbolicIndexingInterface = "0.3.45"
Symbolics = "7.2.0"
julia = "1.8, 1.11"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CUDA", "RecursiveArrayTools"]
