name = "CellBasedModels"
uuid = "388cb286-f2b1-4654-a3bb-2e137a39c658"
authors = ["Gabriel Torregrosa Cort√©s"]
version = "0.1.1"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CellBasedModelsGPUExt = "CUDA"

[compat]
Adapt = "4.4.0"
ArrayInterface = "7.20.0"
BenchmarkTools = "1.6.0"
CSV = "0.10, 1"
CUDA = "4, 5"
DataFrames = "1, 2"
DifferentialEquations = "7"
Distributions = "0.25, 1"
JLD2 = "0.4, 1"
MacroTools = "0.5"
OrderedCollections = "1"
Printf = "1.11.0"
ProgressMeter = "1.7"
RecursiveArrayTools = "3.37.1"
SpecialFunctions = "2"
StaticArrays = "1.9.15"
StaticArraysCore = "1.4.3"
SymbolicIndexingInterface = "0.3.45"
julia = "1.8, 1.11"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CUDA", "RecursiveArrayTools"]
